---
title: "sir-metagenomics-analysis"
author: "Angela Jiang"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)

```

## Read the data

```{r data}

# PRISM data
metadata <- read.csv("Tables/metadata_prism.tsv", sep="\t")

# Reads mapped table
reads <- read.csv("Tables/PRISM_all_data.tsv", sep="\t")

# Raw data in Tables/ folder
converter_status <- read.csv("Tables/sample_to_converter_PRISM.csv", sep=",")

# Merging reads table with metadata table by SRS number
reads_to_metadata <- merge(metadata, reads, by="Sample")

# Merge with converter status by Sample ID
total <- merge(reads_to_metadata, converter_status, by="Sample_ID")
```

## CPM calculation

```{r cpm, echo=FALSE}
processed <- total %>%
  filter(total_reads >= 1000000) %>%
  mutate(sir_species_cpm = reads_mapped_sir_species / total_reads * 1000000) %>%
  mutate(ismA_species_cpm = reads_mapped_ismA_species / total_reads * 1000000) %>%
  mutate(ismA_gene_cpm = reads_mapped_ismA_gene / total_reads * 1000000) %>%
  mutate(sir_gene_cpm = reads_mapped_sir_gene / total_reads * 1000000)

# Any sample with above 2 cpm for ismA/sir is considered an encoder of that gene
processed <- processed %>%
  mutate(ismA_Encoder = ifelse(ismA_gene_cpm >= 2, "Encoder", "Non-Encoder")) %>%
  mutate(sir_Encoder = ifelse(sir_gene_cpm >= 2, "Encoder", "Non-Encoder"))

ismA_summary <- processed %>%
  group_by(Converter, ismA_Encoder) %>%
  summarise(Count = n(), .groups = "drop") %>%
  group_by(Converter) %>%
  mutate(Percentage = (Count / sum(Count)) * 100)

sir_summary <- processed %>%
  group_by(Converter, sir_Encoder) %>%
  summarise(Count = n(), .groups = "drop") %>%
  group_by(Converter) %>%
  mutate(Percentage = (Count / sum(Count)) * 100)

```

## Plot results

```{r plot}

library(patchwork)

sir_summary$sir_Encoder <- factor(sir_summary$sir_Encoder, levels = c("Non-Encoder", "Encoder"))
ismA_summary$ismA_Encoder <- factor(ismA_summary$ismA_Encoder, levels = c("Non-Encoder", "Encoder"))

sir_summary$Converter <- factor(sir_summary$Converter, levels = c("Converter", "Non-Converter"), labels = c("Detected", "Undetected"))
ismA_summary$Converter <- factor(ismA_summary$Converter, levels = c("Converter", "Non-Converter"), labels = c("Detected", "Undetected"))

p1 <- ggplot(sir_summary, aes(x = Converter, y = Percentage, fill = sir_Encoder)) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values = c("Encoder" = "#ff7f00", "Non-Encoder" = "gray")) +  # Custom colors
  labs(title = "ismA vs ecSIR and Conversion of Cholesterol",
       x = "Converter Status",
       xlabs = ("Detected, Undetected"),
       y = "Percentage") +
  theme_minimal()

p2 <- ggplot(ismA_summary, aes(x = Converter, y = Percentage, fill = ismA_Encoder)) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values = c("Encoder" = "#377eb8", "Non-Encoder" = "gray")) +  # Custom colors
  labs(
       x = "Coprostanol",
       xlabs = ("Detected, Undetected"),
       y = "Percentage") +
  theme_minimal()

p1 + p2

```

