---
title: "SpiR-metagenomics-analysis"
author: "Angela Jiang"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(tidyr)
library(tibble)
library(rstudioapi)

```

## Read the data

```{r data}
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
data <- read.csv("../Tables/Supplemental_Table_Metagenomics.txt", sep="\t")

```

## CPM calculation

```{r cpm, echo=FALSE}
processed <- data %>%
  filter(total_reads >= 1000000) %>%
  mutate(SpiR_species_cpm = reads_mapped_SpiR_species / total_reads * 1000000) %>%
  mutate(ismA_species_cpm = reads_mapped_ismA_species / total_reads * 1000000) %>%
  mutate(ismA_gene_cpm = reads_mapped_ismA_gene / total_reads * 1000000) %>%
  mutate(SpiR_gene_cpm = reads_mapped_SpiR_gene / total_reads * 1000000)

# Any sample with above 1 cpm for ismA/SpiR is considered to have that gene
processed <- processed %>%
  mutate(ismA_Encoder = ifelse(ismA_gene_cpm >= 1, "Encoder", "Non-Encoder")) %>%
  mutate(SpiR_Encoder = ifelse(SpiR_gene_cpm >= 1, "Encoder", "Non-Encoder")) %>%
  mutate(ismA_species_Encoder = ifelse(ismA_species_cpm >= 18000, "Encoder", "Non-Encoder")) %>%
  mutate(SpiR_species_Encoder = ifelse(SpiR_species_cpm >= 18000, "Encoder", "Non-Encoder")) 
```

```{r func_plot_perc}

# function to plot bar graph for SpiR
plot_summary_SpiR <- function(data, study) {
  SpiR_summary <- data %>%
    filter(Study == study) %>%
    mutate(Converter = ifelse(area_coprostanol > get(paste(study, "_area_threshold", sep="")), "Converter", "Non-Converter")) %>%
    group_by(Converter, SpiR_Encoder) %>%
    summarise(Count = n(), .groups = "drop") %>%
    group_by(Converter) %>%
    mutate(Percentage = (Count / sum(Count)) * 100)
  
  SpiR_summary[['SpiR_Encoder']] <- factor(SpiR_summary[['SpiR_Encoder']], levels = c("Non-Encoder", "Encoder"))
  
  p <- ggplot(SpiR_summary, aes(x = Converter, y = Count, fill = SpiR_Encoder)) +
    geom_bar(stat = "identity") +
    scale_fill_manual(values = c("Encoder" = "#377eb8", "Non-Encoder" = "gray")) +  # Custom colors
    labs(
      title = study,
      x = "Fecal Coprostanone",
      xlabs = "Detected, Undetected",
      y = "Count"
    ) +
    theme_classic() +
    guides(fill = guide_legend(title = "ecSpiR")) +
    theme(
      axis.text.x = element_text(angle = 45, hjust = 1, family = "Arial"),
      legend.position = "none",
      axis.title = element_text(size = 16, family = "Arial"),  # Axis titles
      axis.text = element_text(size = 16, family = "Arial"),   # Axis labels (tick marks)
      plot.title = element_text(size = 16, family = "Arial"),  # Plot title
      legend.title = element_text(size = 16, family = "Arial"),  # Legend title
      legend.text = element_text(size = 16, family = "Arial")
    ) +
    geom_text(
      data = subset(SpiR_summary, SpiR_Encoder == "Encoder"),
      aes(label = paste0(round(Percentage, 1), "%")),
      vjust = -0.5,
      color = "black",
      size = 5
    )
  
    return(list(plot = p, summary_table = SpiR_summary))
}

plot_summary_ismA <- function(data, study) {
  SpiR_summary <- data %>%
    filter(Study == study) %>%
    mutate(Converter = ifelse(area_coprostanol > get(paste(study, "_area_threshold", sep="")), "Converter", "Non-Converter")) %>%
    group_by(Converter, ismA_Encoder) %>%
    summarise(Count = n(), .groups = "drop") %>%
    group_by(Converter) %>%
    mutate(Percentage = (Count / sum(Count)) * 100)
  
  SpiR_summary[['ismA_Encoder']] <- factor(SpiR_summary[['ismA_Encoder']], levels = c("Non-Encoder", "Encoder"))
  
  p <- ggplot(SpiR_summary, aes(x = Converter, y = Count, fill = ismA_Encoder)) +
    geom_bar(stat = "identity") +
    scale_fill_manual(values = c("Encoder" = "#ff7f00", "Non-Encoder" = "gray")) +
    labs(
      title = study,
      x = "Fecal Coprostanone",
      xlabs = "Detected, Undetected",
      y = "Count"
    ) +
    theme_classic() +
    guides(fill = guide_legend(title = "ismA")) +
    theme(
      axis.text.x = element_text(angle = 45, hjust = 1, family = "Arial"),
      legend.position = "none",
      axis.title = element_text(size = 16, family = "Arial"),  # Axis titles
      axis.text = element_text(size = 16, family = "Arial"),   # Axis labels (tick marks)
      plot.title = element_text(size = 16, family = "Arial"),  # Plot title
      legend.title = element_text(size = 16, family = "Arial"),  # Legend title
      legend.text = element_text(size = 16, family = "Arial")
    ) +
    geom_text(
      data = subset(SpiR_summary, ismA_Encoder == "Encoder"),
      aes(label = paste0(round(Percentage, 1), "%")),
      vjust = -0.5,
      color = "black",
      size = 5
    )
  
  return(list(plot = p, summary_table = SpiR_summary))
}

```

```{r plot_func_species}

# function to plot bar graph for species
plot_summary_SpiR_species <- function(data, study) {
  SpiR_summary <- data %>%
    filter(Study == study) %>%
    mutate(Converter = ifelse(area_coprostanol > get(paste(study, "_area_threshold", sep="")), "Converter", "Non-Converter")) %>%
    group_by(Converter, SpiR_species_Encoder) %>%
    summarise(Count = n(), .groups = "drop") %>%
    group_by(Converter) %>%
    mutate(Percentage = (Count / sum(Count)) * 100)
  
  SpiR_summary[['SpiR_species_Encoder']] <- factor(SpiR_summary[['SpiR_species_Encoder']], levels = c("Non-Encoder", "Encoder"))
  
  p <- ggplot(SpiR_summary, aes(x = Converter, y = Count, fill = SpiR_species_Encoder)) +
    geom_bar(stat = "identity") +
    scale_fill_manual(values = c("Encoder" = "#377eb8", "Non-Encoder" = "gray")) +  # Custom colors
    labs(
      title = study,
      x = "Fecal Coprostanone",
      xlabs = "Detected, Undetected",
      y = "Count"
    ) +
    theme_classic() +
    guides(fill = guide_legend(title = "ecSpiR")) +
    theme(
      axis.text.x = element_text(angle = 45, hjust = 1, family = "Arial"),
      legend.position = "none",
      axis.title = element_text(size = 16, family = "Arial"),  # Axis titles
      axis.text = element_text(size = 16, family = "Arial"),   # Axis labels (tick marks)
      plot.title = element_text(size = 16, family = "Arial"),  # Plot title
      legend.title = element_text(size = 16, family = "Arial"),  # Legend title
      legend.text = element_text(size = 16, family = "Arial")
    ) +
    geom_text(
      data = subset(SpiR_summary, SpiR_species_Encoder == "Encoder"),
      aes(label = paste0(round(Percentage, 1), "%")),
      vjust = -0.5,
      color = "black",
      size = 5
    )
  
  return(list(plot = p, summary_table = SpiR_summary))
}

plot_summary_ismA_species <- function(data, study) {
  ismA_summary_2 <- data %>%
    filter(Study == study) %>%
    mutate(Converter = ifelse(area_coprostanol > get(paste(study, "_area_threshold", sep="")), "Converter", "Non-Converter")) %>%
    group_by(Converter, ismA_species_Encoder) %>%
    summarise(Count = n(), .groups = "drop") %>%
    group_by(Converter) %>%
    mutate(Percentage = (Count / sum(Count)) * 100)
  
  ismA_summary_2[['ismA_species_Encoder']] <- factor(ismA_summary_2[['ismA_species_Encoder']], levels = c("Non-Encoder", "Encoder"))
  
  ismA_summary_2
  
  p2_2 <- ggplot(ismA_summary_2, aes(x = Converter, y = Count, fill = ismA_species_Encoder)) +
    geom_bar(stat = "identity") +
    scale_fill_manual(values = c("Encoder" = "#ff7f00", "Non-Encoder" = "gray")) +
    labs(
      title = study,
      x = "Fecal Coprostanone",
      xlabs = "Detected, Undetected",
      y = "Count"
    ) +
    theme_classic() +
    guides(fill = guide_legend(title = "ismA")) +
    theme(
      axis.text.x = element_text(angle = 45, hjust = 1, family = "Arial"),
      legend.position = "none",
      axis.title = element_text(size = 16, family = "Arial"),
      axis.text = element_text(size = 16, family = "Arial"), 
      plot.title = element_text(size = 16, family = "Arial"),  # Plot title
      legend.title = element_text(size = 16, family = "Arial"),  # Legend title
      legend.text = element_text(size = 16, family = "Arial")
    ) +
    geom_text(
      data = subset(ismA_summary_2, ismA_species_Encoder == "Encoder"),
      aes(label = paste0(round(Percentage, 1), "%")),
      vjust = -0.5,
      color = "black",
      size = 5
    )
  
  return(list(plot = p2_2, summary_table = ismA_summary_2))
}

```

## Plot results for PRISM

```{r plot}

library(patchwork)

PRISM_area_threshold <- 1e6

p1 <- plot_summary_SpiR(processed, "PRISM")

p2 <- plot_summary_ismA(processed, "PRISM")

prism <- p1$plot + p2$plot

prism

p1_s <- plot_summary_SpiR_species(processed, "PRISM")

p2_s <- plot_summary_ismA_species(processed, "PRISM")

prism_s <- p1_s$plot + p2_s$plot

prism_s

```

## Plot results for HMP2

```{r plot_hmp2}

library(patchwork)

HMP2_area_threshold <- 1e6

p3 <- plot_summary_SpiR(processed, "HMP2")

p4 <- plot_summary_ismA(processed, "HMP2")

hmp2 <- p3$plot + p4$plot

hmp2

p3_s <- plot_summary_SpiR_species(processed, "HMP2")

p4_s <- plot_summary_ismA_species(processed, "HMP2")

```


## Plot results for PROTECT

```{r plot_protect}

library(patchwork)

PROTECT_area_threshold <- 1e5

p5 <- plot_summary_SpiR(processed, "PROTECT")

p6 <- plot_summary_ismA(processed, "PROTECT")

protect <- p5$plot + p6$plot

protect

p5_s <- plot_summary_SpiR_species(processed, "PROTECT")

p6_s <- plot_summary_ismA_species(processed, "PROTECT")

```

# Plot all studies together

```{r}

combined_plot <- p3$plot + p4$plot + p1$plot + p2$plot + p5$plot + p6$plot  + plot_layout(guides = "collect", axes = "collect", nrow = 1, widths=10)

combined_plot

ggsave("Fig_Propotions.svg", plot = combined_plot, device = "svg", width = 89 * 3 / 25.4, height = 89 * 2 * 0.75 / 25.4, units = "in")

```

# Plot IBD association with each gene

```{r disease_plot}

disease_summary_ismA <- processed %>%
  mutate(Diagnosis = factor(Diagnosis, levels = c("nonIBD", "CD", "UC")))  %>%
  mutate(ismA_Encoder = factor(ismA_Encoder, levels = c("Encoder", "Non-Encoder")))  %>%
  group_by(Diagnosis, ismA_Encoder, Study) %>%
  summarise(Count = n(), .groups = "drop") %>%
  group_by(Diagnosis) %>%
  mutate(Percentage = (Count / sum(Count)) * 100)

disease_summary_SpiR <- processed %>%
  mutate(Diagnosis = factor(Diagnosis, levels = c("nonIBD", "CD", "UC")))  %>%
  mutate(SpiR_Encoder = factor(SpiR_Encoder, levels = c("Encoder", "Non-Encoder")))  %>%
  group_by(Diagnosis, SpiR_Encoder, Study) %>%
  summarise(Count = n(), .groups = "drop") %>%
  group_by(Diagnosis) %>%
  mutate(Percentage = (Count / sum(Count)) * 100)


# For disease_summary_ismA plot
p_ismA <- ggplot(disease_summary_ismA, aes(x = Diagnosis, y = Count, fill = ismA_Encoder)) +
  geom_bar(stat = "identity", position = "stack") +
  scale_fill_manual(values = c("Encoder" = "#ff7f00", "Non-Encoder" = "gray")) +
  labs(
    x = "Diagnosis",
    y = "Samples",
    title = "ismA Encoder Status by Diagnosis"
  ) +
  facet_wrap(~Study) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, family = "Arial"), legend.position = "none",
        axis.title = element_text(size = 16, family = "Arial"),  # Axis titles
    axis.text = element_text(size = 16, family = "Arial"),   # Axis labels (tick marks)
    plot.title = element_text(size = 16, family = "Arial"),  # Plot title
    legend.title = element_text(size = 16, family = "Arial"),  # Legend title
    legend.text = element_text(size = 16, family = "Arial")) 

# For disease_summary_SpiR plot
p_SpiR <- ggplot(disease_summary_SpiR, aes(x = Diagnosis, y = Count, fill = SpiR_Encoder)) +
  geom_bar(stat = "identity", position = "stack") +
  scale_fill_manual(values = c("Encoder" = "#377eb8", "Non-Encoder" = "gray")) +
  labs(
    x = "Diagnosis",
    y = "Samples",
    title = "SpiR Encoder Status by Diagnosis"
  ) +
  facet_wrap(~Study) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, family = "Arial"), legend.position = "none",
        axis.title = element_text(size = 16, family = "Arial"), 
    axis.text = element_text(size = 16, family = "Arial"),  
    plot.title = element_text(size = 16, family = "Arial"), 
    legend.title = element_text(size = 16, family = "Arial"),
    legend.text = element_text(size = 16, family = "Arial")) 



d_all <- p_SpiR + p_ismA

d_all

ggsave("Fig_Disease.svg", plot = d_all, device = "svg", width = 89 * 3 / 25.4, height = 89 * 2 * 0.75 / 25.4, units = "in")


```

# Fischer tests

```{r stats_tests}

# Proportions tests
# HMP2 for converters
prop.test(matrix(c(175,21,112,84), ncol = 2, byrow = TRUE), alternative="greater")

# PRISM for converters
prop.test(matrix(c(80,5,53,32), ncol = 2, byrow = TRUE), alternative="greater")

# PROTECT for converters
prop.test(matrix(c(32,12,24,20), ncol = 2, byrow = TRUE), alternative="greater")


# Fischers test

# PRISM
SpiR_matrix_prism <- p1$summary_table %>%
  select(Converter, SpiR_Encoder, Count) %>%
  pivot_wider(names_from = Converter, values_from = Count) %>%
  column_to_rownames("SpiR_Encoder")

SpiR_matrix_prism[is.na(SpiR_matrix_prism)] <- 0

fischer_prism <- fisher.test(as.matrix(SpiR_matrix_prism)+1)

fischer_prism

ismA_matrix_prism <- p2$summary_table %>%
  select(Converter, ismA_Encoder, Count) %>%
  pivot_wider(names_from = Converter, values_from = Count) %>%
  column_to_rownames("ismA_Encoder")

ismA_matrix_prism[is.na(ismA_matrix_prism)] <- 0

fischer_prism_ismA <- fisher.test(as.matrix(ismA_matrix_prism)+1)

fischer_prism_ismA

# HMP2
SpiR_matrix_hmp2 <- p3$summary_table %>%
  select(Converter, SpiR_Encoder, Count) %>%
  pivot_wider(names_from = Converter, values_from = Count) %>%
  column_to_rownames("SpiR_Encoder")

SpiR_matrix_hmp2[is.na(SpiR_matrix_hmp2)] <- 0

SpiR_hmp2_fischer <- fisher.test(as.matrix(SpiR_matrix_hmp2)+1)

SpiR_hmp2_fischer

ismA_matrix_hmp2 <- p4$summary_table %>%
  select(Converter, ismA_Encoder, Count) %>%
  pivot_wider(names_from = Converter, values_from = Count) %>%
  column_to_rownames("ismA_Encoder")

ismA_matrix_hmp2[is.na(ismA_matrix_hmp2)] <- 0

ismA_hmp2_fischer <- fisher.test(as.matrix(ismA_matrix_hmp2)+1)

ismA_hmp2_fischer

# PROTECT
SpiR_matrix_protect <- p5$summary_table %>%
  select(Converter, SpiR_Encoder, Count) %>%
  pivot_wider(names_from = Converter, values_from = Count) %>%
  column_to_rownames("SpiR_Encoder")

SpiR_matrix_protect[is.na(SpiR_matrix_protect)] <- 0

protect_SpiR_fischer <- fisher.test(as.matrix(SpiR_matrix_protect)+1)

protect_SpiR_fischer

ismA_matrix_protect <- p6$summary_table %>%
  select(Converter, ismA_Encoder, Count) %>%
  pivot_wider(names_from = Converter, values_from = Count) %>%
  column_to_rownames("ismA_Encoder")

ismA_matrix_protect[is.na(ismA_matrix_protect)] <- 0

protect_ismA_fischer <- fisher.test(as.matrix(ismA_matrix_protect)+1)

protect_ismA_fischer
```

# Fischer tests for species

```{r stats_tests_s}

# Proportions tests
# HMP2 for converters
prop.test(matrix(c(117,79,68,128), ncol = 2, byrow = TRUE), alternative="greater")

# PRISM for converters
prop.test(matrix(c(76,9,40,44), ncol = 2, byrow = TRUE), alternative="greater")

# PROTECT for converters
prop.test(matrix(c(30,14,17,27), ncol = 2, byrow = TRUE), alternative="greater")


# Fischers test

# PRISM
SpiR_matrix_prism <- p1_s$summary_table %>%
  select(Converter, SpiR_species_Encoder, Count) %>%
  pivot_wider(names_from = Converter, values_from = Count) %>%
  column_to_rownames("SpiR_species_Encoder")

SpiR_matrix_prism[is.na(SpiR_matrix_prism)] <- 0

fischer_prism <- fisher.test(as.matrix(SpiR_matrix_prism)+1)

fischer_prism

ismA_matrix_prism <- p2_s$summary_table %>%
  filter(!is.na(ismA_species_Encoder)) %>%
  select(Converter, ismA_species_Encoder, Count) %>%
  pivot_wider(names_from = Converter, values_from = Count) %>%
  column_to_rownames("ismA_species_Encoder")

ismA_matrix_prism[is.na(ismA_matrix_prism)] <- 0

fischer_prism_ismA <- fisher.test(as.matrix(ismA_matrix_prism)+1)

fischer_prism_ismA

# HMP2
SpiR_matrix_hmp2 <- p3_s$summary_table %>%
  select(Converter, SpiR_species_Encoder, Count) %>%
  pivot_wider(names_from = Converter, values_from = Count) %>%
  column_to_rownames("SpiR_species_Encoder")

SpiR_matrix_hmp2[is.na(SpiR_matrix_hmp2)] <- 0

SpiR_hmp2_fischer <- fisher.test(as.matrix(SpiR_matrix_hmp2)+1)

SpiR_hmp2_fischer

ismA_matrix_hmp2 <- p4_s$summary_table %>%
  select(Converter, ismA_species_Encoder, Count) %>%
  pivot_wider(names_from = Converter, values_from = Count) %>%
  column_to_rownames("ismA_species_Encoder")

ismA_matrix_hmp2[is.na(ismA_matrix_hmp2)] <- 0

ismA_hmp2_fischer <- fisher.test(as.matrix(ismA_matrix_hmp2)+1)

ismA_hmp2_fischer

# PROTECT
SpiR_matrix_protect <- p5_s$summary_table %>%
  select(Converter, SpiR_species_Encoder, Count) %>%
  pivot_wider(names_from = Converter, values_from = Count) %>%
  column_to_rownames("SpiR_species_Encoder")

SpiR_matrix_protect[is.na(SpiR_matrix_protect)] <- 0

protect_SpiR_fischer <- fisher.test(as.matrix(SpiR_matrix_protect)+1)

protect_SpiR_fischer

ismA_matrix_protect <- p6_s$summary_table %>%
  select(Converter, ismA_species_Encoder, Count) %>%
  pivot_wider(names_from = Converter, values_from = Count) %>%
  column_to_rownames("ismA_species_Encoder")

ismA_matrix_protect[is.na(ismA_matrix_protect)] <- 0

protect_ismA_fischer <- fisher.test(as.matrix(ismA_matrix_protect)+1)

protect_ismA_fischer
```


```{r plot_overlap_func}

# Define the function

library(dplyr)
library(ggplot2)

# Define the function
plot_study_metabolite <- function(data, Study, area_threshold) {
  # Filter data for the given Study and create necessary variables
  processed2 <- data %>%
    filter(Study == Study) %>%
    mutate(Converter = ifelse(area_coprostanol > area_threshold, "Converter", "Non-Converter")) %>%
    mutate(bar_color = case_when(
      SpiR_species_Encoder == "Encoder" & ismA_species_Encoder == "Encoder" ~ "#B6ADC7",
      SpiR_species_Encoder == "Encoder" & ismA_species_Encoder == "Non-Encoder" ~ "#A3BDD0",
      SpiR_species_Encoder == "Non-Encoder" & ismA_species_Encoder == "Encoder" ~ "#E6B88C",
      TRUE ~ "#c9c9c9"  # Default case (if none of the above are true)
    ))

  # Set the levels of 'bar_color' to ensure the deSpiRed order in the plot
  processed2$bar_color <- factor(processed2$bar_color, levels = c("#c9c9c9", "#E6B88C", "#A3BDD0", "#B6ADC7"))

  # Calculate the percentage for each bar
  processed2 <- processed2 %>%
    group_by(Converter, bar_color) %>%
    mutate(percentage = n() / sum(n()) * 100) %>%
    ungroup()

  # Calculate the count for each bar
  count_data <- processed2 %>%
    group_by(Converter, bar_color) %>%
    summarise(Count = n()) %>%
    ungroup()

  # Create the ggplot using the filtered data
  p <- ggplot(processed2, aes(x = Converter, fill = bar_color)) +
    geom_bar(stat = "count") +  # Use count instead of manually passing y values
    scale_fill_identity() +  # Use the color directly from the 'bar_color' column
    labs(
      x = "Fecal Coprostanone",
      xlabs = ("Detected, Undetected"),
      y = "Count") +
    theme_classic() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1, family = "Arial"), 
          legend.position = "none",
          axis.title = element_text(size = 16, family = "Arial"),  # Axis titles
          axis.text = element_text(size = 16, family = "Arial"),   # Axis labels (tick marks)
          plot.title = element_text(size = 16, family = "Arial"),  # Plot title
          legend.title = element_text(size = 16, family = "Arial"),  # Legend title
          legend.text = element_text(size = 16, family = "Arial"))

  # Return the plot
  return(p)
}

prism_overlap <- plot_overlap(processed, "PRISM", PRISM_area_threshold)

hmp2_overlap <- plot_overlap(processed, "HMP2", HMP2_area_threshold)

protect_overlap <- plot_overlap(processed, "PROTECT", PROTECT_area_threshold)

combined_overlap <-  hmp2_overlap + prism_overlap + protect_overlap + plot_layout(guides = "collect", nrow = 1, widths=10)

combined_overlap

ggsave("Fig_Overlap_species.svg", plot = combined_overlap, device = "svg", width = 89 * 3 / 25.4, height = 89 * 2 * 0.75 / 25.4, units = "in")

```

